--- panda3d-master/dtool/src/interrogatedb/py_panda.cxx	2019-08-26 10:07:58.000000000 +0200
+++ panda3d-master.32/dtool/src/interrogatedb/py_panda.cxx	2019-09-01 19:10:50.991187599 +0200
@@ -165,7 +165,8 @@
 /**
  * Raises a TypeError with the given message, and returns NULL.
  */
-PyObject *Dtool_Raise_TypeError(const char *message) {
+
+PyAPI_DATA(PyObject) *Dtool_Raise_TypeError(const char *message) {
   // PyErr_Restore is what PyErr_SetString would have ended up calling
   // eventually anyway, so we might as well just get to the point.
   Py_INCREF(PyExc_TypeError);
@@ -177,6 +178,7 @@
   return nullptr;
 }
 
+
 /**
  * Raises a TypeError of the form: function_name() argument n must be type,
  * not type for a given object passed to a function.
@@ -636,7 +638,7 @@
       if (main_module == NULL) {
         interrogatedb_cat.warning() << "Unable to import __main__\n";
       }
-      
+
       // Extract the __file__ attribute, if present.
       Filename main_dir;
       PyObject *file_attr = nullptr;
